stages:
  - setup
  - build_x64_base
  - build_x64_universal
  - build_x86_base
  - build_x86_universal

before_script:
  - "mkdir -p $TMPDIR"
  - "ln -s $HOME/packer_cache packer_cache"
  - "export VERSION=v$(date +'%Y%m%d')"

variables:
  TMPDIR: "$CI_PROJECT_DIR/../tmp"

setup_environment:
  stage: setup
  script:
    - vagrant plugin repair
    - vagrant plugin install vagrant-serverspec

build_w10_LTSC_x64_job:
  stage: build_x64_base
  script:
    - "./build.sh LTSC x64 base $VERSION"
    - "bash tests/test.sh LTSC x64 base $VERSION"
    - "mv boxes/*.box $HOME/boxes/"
    - "mv ./output/windows10-$RELEASE-eval-$ARCH-base $HOME/boxes/"
  tags:
    - box_build
  allow_failure: true

build_w10_LTSC_x64_universal_job:
  stage: build_x64_universal
  script:
    - "mkdir -p ./output && mv $HOME/boxes/windows10-$RELEASE-eval-$ARCH-base ./output/"
    - "./build.sh LTSC x64 universal $VERSION"
    - "bash tests/test.sh LTSC x64 universal $VERSION"
    - "mv boxes/*.box $HOME/boxes/"
  tags:
    - box_build
  allow_failure: true

build_w10_LTSC_x86_base_job:
  stage: build_x86_base
  script:
    - "./build.sh LTSC x86 base $VERSION"
    - "./tests/test.sh LTSC x86 base $VERSION"
    - "mv boxes/*.box $HOME/boxes/"
    - "mv ./output/windows10-$RELEASE-eval-$ARCH-base $HOME/boxes/"
  tags:
    - box_build
  allow_failure: true

build_w10_LTSC_x86_universal_job:
  stage: build_x86_universal
  script:
    - "mkdir -p ./output && mv $HOME/boxes/windows10-$RELEASE-eval-$ARCH-base ./output/"
    - "./build.sh LTSC x86 universal $VERSION"
    - "./tests/test.sh LTSC x86 universal $VERSION"
    - "mv boxes/*.box $HOME/boxes/"
  tags:
    - box_build
  allow_failure: true

build_w10_1909_x64_job:
  stage: build_x64_base
  script:
    - "./build.sh 1909 x64 base $VERSION"
    - "./tests/test.sh 1909 x64 base $VERSION"
    - "mv boxes/*.box $HOME/boxes/"
    - "mv ./output/windows10-$RELEASE-eval-$ARCH-base $HOME/boxes/"
  tags:
    - box_build
  allow_failure: true

build_w10_1909_x64_universal_job:
  stage: build_x64_universal
  script:
    - "mkdir -p ./output && mv $HOME/boxes/windows10-$RELEASE-eval-$ARCH-base ./output/"
    - "./build.sh 1909 x64 universal $VERSION"
    - "./tests/test.sh 1909 x64 universal $VERSION"
    - "mv boxes/*.box $HOME/boxes/"
  tags:
    - box_build
  allow_failure: true

build_w10_1909_x86_base_job:
  stage: build_x86_base
  script:
    - "./build.sh 1909 x86 base $VERSION"
    - "./tests/test.sh 1909 x86 base $VERSION"
    - "mv boxes/*.box $HOME/boxes/"
    - "mv ./output/windows10-$RELEASE-eval-$ARCH-base $HOME/boxes/"
  tags:
    - box_build
  allow_failure: true

build_w10_1909_x86_universal_job:
  stage: build_x86_universal
  script:
    - "mkdir -p ./output && mv $HOME/boxes/windows10-$RELEASE-eval-$ARCH-base ./output/"
    - "./build.sh 1909 x86 universal $VERSION"
    - "./tests/test.sh 1909 x86 universal $VERSION"
    - "mv boxes/*.box $HOME/boxes/"
  tags:
    - box_build
  allow_failure: true
