stages:
  - setup
  - build_x64_base
  - build_x64_universal
  - build_x86_base
  - build_x86_universal
  - upload
  - release

before_script:
  - "mkdir -p $TMPDIR"
  - "ln -s $HOME/packer_cache packer_cache"
  - "export VERSION=$(cat .ci_status/version)"

variables:
  TMPDIR: "$CI_PROJECT_DIR/../tmp"

setup_environment:
  before_script: []
  stage: setup
  script:
    - mkdir -p .ci_status && echo $(date +'%Y%m%d') > .ci_status/version
    - vagrant plugin repair
    - vagrant plugin install vagrant-serverspec
  artifacts:
    paths:
      - .ci_status/

build_w10_LTSC_x64_job:
  stage: build_x64_base
  script:
    - "./build.sh LTSC x64 base $VERSION"
    - "./tests/test.sh LTSC x64 base $VERSION"
    - "mv boxes/*.box $HOME/boxes/"
    - "mv ./output/windows10-LTSC-eval-x64-base $HOME/boxes/"
  tags:
    - box_build

build_w10_LTSC_x64_universal_job:
  stage: build_x64_universal
  script:
    - "mkdir -p ./output && mv $HOME/boxes/windows10-LTSC-eval-x64-base ./output/"
    - "./build.sh LTSC x64 universal $VERSION"
    - "bash tests/test.sh LTSC x64 universal $VERSION"
    - "mv boxes/*.box $HOME/boxes/"
  tags:
    - box_build

build_w10_LTSC_x86_base_job:
  stage: build_x86_base
  script:
    - "./build.sh LTSC x86 base $VERSION"
    - "./tests/test.sh LTSC x86 base $VERSION"
    - "mv boxes/*.box $HOME/boxes/"
    - "mv ./output/windows10-LTSC-eval-x86-base $HOME/boxes/"
  tags:
    - box_build

build_w10_LTSC_x86_universal_job:
  stage: build_x86_universal
  script:
    - "mkdir -p ./output && mv $HOME/boxes/windows10-LTSC-eval-x86-base ./output/"
    - "./build.sh LTSC x86 universal $VERSION"
    - "./tests/test.sh LTSC x86 universal $VERSION"
    - "mv boxes/*.box $HOME/boxes/"
  tags:
    - box_build

build_w10_1909_x64_job:
  stage: build_x64_base
  script:
    - "./build.sh 1909 x64 base $VERSION"
    - "./tests/test.sh 1909 x64 base $VERSION"
    - "mv boxes/*.box $HOME/boxes/"
    - "mv ./output/windows10-1909-eval-x64-base $HOME/boxes/"
  tags:
    - box_build

build_w10_1909_x64_universal_job:
  stage: build_x64_universal
  script:
    - "mkdir -p ./output && mv $HOME/boxes/windows10-1909-eval-x64-base ./output/"
    - "./build.sh 1909 x64 universal $VERSION"
    - "./tests/test.sh 1909 x64 universal $VERSION"
    - "mv boxes/*.box $HOME/boxes/"
  tags:
    - box_build

build_w10_1909_x86_base_job:
  stage: build_x86_base
  script:
    - "./build.sh 1909 x86 base $VERSION"
    - "./tests/test.sh 1909 x86 base $VERSION"
    - "mv boxes/*.box $HOME/boxes/"
    - "mv ./output/windows10-1909-eval-x86-base $HOME/boxes/"
  tags:
    - box_build

build_w10_1909_x86_universal_job:
  stage: build_x86_universal
  script:
    - "mkdir -p ./output && mv $HOME/boxes/windows10-1909-eval-x86-base ./output/"
    - "./build.sh 1909 x86 universal $VERSION"
    - "./tests/test.sh 1909 x86 universal $VERSION"
    - "mv boxes/*.box $HOME/boxes/"
  tags:
    - box_build

upload_images_job:
  stage: upload
  script:
    - "./upload.sh LTSC x64 base $VERSION"
    - "./upload.sh LTSC x86 base $VERSION"
    - "./upload.sh 1909 x64 base $VERSION"
    - "./upload.sh 1909 x86 base $VERSION"
    - "./upload.sh LTSC x64 universal $VERSION"
    - "./upload.sh LTSC x86 universal $VERSION"
    - "./upload.sh 1909 x64 universal $VERSION"
    - "./upload.sh 1909 x86 universal $VERSION"
  tags:
    - box_build
  when: manual

release_images_job:
  stage: release
  script:
    - "./release.sh LTSC x64 base $VERSION"
    - "./release.sh LTSC x86 base $VERSION"
    - "./release.sh 1909 x64 base $VERSION"
    - "./release.sh 1909 x86 base $VERSION"
    - "./release.sh LTSC x64 universal $VERSION"
    - "./release.sh LTSC x86 universal $VERSION"
    - "./release.sh 1909 x64 universal $VERSION"
    - "./release.sh 1909 x86 universal $VERSION"
  tags:
    - box_build
  when: manual
