stages:
  - setup
  - build_x64_base
  - build_x64_universal
  - build_x86_base
  - build_x86_universal

before_script:
  - "mkdir -p $TMPDIR"
  - "ln -s $HOME/packer_cache packer_cache"
  - "git submodule sync --recursive"
  - "git submodule update --init --recursive"

variables:
  TMPDIR: "$CI_PROJECT_DIR/../tmp"

setup_environment:
  stage: setup
  script:
    - vagrant plugin repair
    - vagrant plugin install vagrant-serverspec

build_w10_LTSC_x64_job:
  stage: build_x64_base
  script:
    - "packer build -only=virtualbox-iso windows_10_x64_LTSC_base.json"
    - "bash tests/test.sh"
    - "mv boxes/*.box $HOME/boxes/"
    - "mv boxes/*.ovf $HOME/boxes/"
  tags:
    - box_build
  allow_failure: true

build_w10_LTSC_x64_universal_job:
  stage: build_x64_universal
  script:
    - "mkdir -p ./output/windows_10_x64_LTSC_base && mv $HOME/boxes/windows10-LTSC-eval-x64-base-*.ovf ./output/windows10-LTSC-eval-x64-base/"
    - "packer build -only=virtualbox-ovf windows_10_x64_LTSC_universal.json"
    - "bash tests/test.sh"
    - "mv boxes/*.box $HOME/boxes/"
  tags:
    - box_build
  allow_failure: true

build_w10_LTSC_x86_base_job:
  stage: build_x86_base
  script:
    - "packer build -only=virtualbox-iso windows_10_x86_LTSC_base.json"
    - "bash tests/test.sh"
    - "mv boxes/*.box $HOME/boxes/"
    - "mv boxes/*.ovf $HOME/boxes/"
  tags:
    - box_build
  allow_failure: true

build_w10_LTSC_x86_universal_job:
  stage: build_x86_universal
  script:
    - "mkdir -p ./output/windows_10_x86_LTSC_base && mv $HOME/boxes/windows10-LTSC-eval-x86-base-*.ovf ./output/windows10-LTSC-eval-x86-base/"
    - "packer build -only=virtualbox-ovf windows_10_x86_LTSC_universal.json"
    - "bash tests/test.sh"
    - "mv boxes/*.box $HOME/boxes/"
  tags:
    - box_build
  allow_failure: true

build_w10_1909_x64_job:
  stage: build_x64_base
  script:
    - "packer build -only=virtualbox-iso windows_10_x64_1909_base.json"
    - "bash tests/test.sh"
    - "mv boxes/*.box $HOME/boxes/"
    - "mv boxes/*.ovf $HOME/boxes/"
  tags:
    - box_build
  allow_failure: true

build_w10_1909_x64_universal_job:
  stage: build_x64_universal
  script:
    - "mkdir -p ./output/windows_10_x64_1909_base && mv $HOME/boxes/windows10-1909-eval-x64-base-*.ovf ./output/windows10-1909-eval-x64-base/"
    - "packer build -only=virtualbox-ovf windows_10_x64_1909_universal.json"
    - "bash tests/test.sh"
    - "mv boxes/*.box $HOME/boxes/"
  tags:
    - box_build
  allow_failure: true

build_w10_1909_x86_base_job:
  stage: build_x86_base
  script:
    - "packer build -only=virtualbox-iso windows_10_x86_1909_base.json"
    - "bash tests/test.sh"
    - "mv boxes/*.box $HOME/boxes/"
    - "mv boxes/*.ovf $HOME/boxes/"
  tags:
    - box_build
  allow_failure: true

build_w10_1909_x86_universal_job:
  stage: build_x86_universal
  script:
    - "mkdir -p ./output/windows_10_x86_1909_base && mv $HOME/boxes/windows10-1909-eval-x86-base-*.ovf ./output/windows10-1909-eval-x86-base/"
    - "packer build -only=virtualbox-ovf windows_10_x86_1909_universal.json"
    - "bash tests/test.sh"
    - "mv boxes/*.box $HOME/boxes/"
  tags:
    - box_build
  allow_failure: true
